name: hackerthon-project
channels:
  - defaults
  - conda-forge
dependencies:
  # Core Python
  - python=3.9
  - pip

  # Web Frameworks (Flask & FastAPI)
  - flask
  - fastapi
  - uvicorn

  # Data Validation & Utils
  - pydantic
  - numpy
  - pandas

  # Pip allows installing packages not in conda channels if needed later
  - pip:
    # - email-validator